export const semanticTokens = Object.freeze({
  color: {
    canvas: '--ui-color-canvas',
    surface: '--ui-color-surface',
    surfaceRaised: '--ui-color-surface-raised',
    textStrong: '--ui-color-text-strong',
    textDefault: '--ui-color-text',
    textMuted: '--ui-color-text-muted',
    actionPrimary: '--ui-color-action',
    actionPrimaryText: '--ui-color-action-text',
    contentPurple: '--ui-color-content-purple',
    contentOrange: '--ui-color-content-orange',
    contentPeach: '--ui-color-content-peach',
    contentCream: '--ui-color-content-cream',
    success: '--ui-color-success',
    warning: '--ui-color-warning',
    danger: '--ui-color-danger',
    info: '--ui-color-info',
  },
  space: [
    '--ui-space-0',
    '--ui-space-1',
    '--ui-space-2',
    '--ui-space-3',
    '--ui-space-4',
    '--ui-space-5',
    '--ui-space-6',
    '--ui-space-8',
    '--ui-space-10',
    '--ui-space-12',
  ],
  radius: {
    sm: '--ui-radius-sm',
    md: '--ui-radius-md',
    lg: '--ui-radius-lg',
    widget: '--ui-radius-widget',
  },
  duration: {
    fast: '--ui-duration-fast',
    normal: '--ui-duration-normal',
    slow: '--ui-duration-slow',
  },
  breakpoint: {
    mobile: 390,
    tablet: 768,
    compact: 1024,
    wide: 1280,
  },
})
